config/routes.rb
Rails.application.routes.draw do
  resources :pictures

  resources :albums
  root 'albums#index'
  get 'show/index'
  devise_for :users
  

end

app/models/album.rb
class Album < ActiveRecord::Base
  #belongs_to :user
   belongs_to :user, :counter_cache => true
  has_many :pictures, :dependent => :destroy

  validates_presence_of :user_id
  validates_presence_of :caption
  validates_length_of   :caption, :within => 1..40
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  belongs_to :album
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         has_many :albums, :dependent => :destroy
  has_many :pictures, :dependent => :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @albums = Album.where(:user_id => current_user.id )
    respond_with(@albums)
  end

  def show
    respond_with(@album)
  end

  def new
    @album = Album.new
    respond_with(@album)
  end

  def edit
  end

  def create
    @album = Album.new(album_params)
    @album.save
    respond_with(@album)
  end

  def update
    @album.update(album_params)
    respond_with(@album)
  end

  def destroy
    @album.destroy
    respond_with(@album)
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def album_params
      params.require(:album).permit(:caption, :description, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
before_action :authenticate_user!
protect_from_forgery with: :exception
  

before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
           #devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
        end




  helper_method :find_album
  def find_album(id)
    Album.find(:first, :conditions => [ "id = ?", id ])
  end

  helper_method :current_album
  def current_album
    @current_album ||= (session[:album_id] ? find_album(session[:album_id]) : nil)
  end

  helper_method :current_album=
  def current_album=(id)
    if current_user
      session[:album_id] = id
    else
      session[:album_id] = nil
    end
  end

  helper_method :all_albums
  def all_albums
    if current_user
      return current_user.albums
    else
      return Album.find(:all, :order => "id DESC", :limit => 20 )
    end
  end

  helper_method :all_pictures
  def all_pictures
    if current_user
      return current_user.pictures
    else
      return Picture.find(:all, :order => "id DESC", :limit => 20 )
    end
  end

  helper_method :user_albums
  def user_albums
    if current_user
      return current_user.albums
    else
      return []
    end
  end

  helper_method :current_user_owns?
  def current_user_owns?(item)
    logged_user = current_user
    return true if logged_user && logged_user.id == item.user_id
    false
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index

    @albumID = session[:albumID]

     
    @pictures = Picture.where(:album_id => @albumID)
    respond_with(@pictures)


  end




  def show
    respond_with(@picture)
  end

  def new
    @picture = Picture.new
    respond_with(@picture)
  end

  def edit
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.save
    respond_with(@picture)
  end

  def update
    @picture.update(picture_params)
    respond_with(@picture)
  end

  def destroy
    @picture.destroy
    respond_with(@picture)
  end

  private
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params.require(:picture).permit(:caption, :description, :user_id, :album_id, :content_type, :width, :height)
    end
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
 
 <p style="margin-top:20px;">Welcome <%= current_user.email %></p><p>user name <%= current_user.name %></p> 
 <h1>Listing albums</h1>



 <div class="table-responsive">
  <table class="table table-striped">
   <thead>
    <tr>
      <th>Album Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.caption %></td>
        <td><%= album.description %></td>
        <td><% @j = album.id %></td>    
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } ,:class => "label label-danger", :style => "color:white;" %></td>
        <td><%= link_to 'Add Pic or View Album', :action => 'index', :controller => 'pictures',title: @j %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Album', new_album_path, :class =>"label label-danger", :style=>"color:white;font-size:15px;" %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p class="alert alert-info">Album added </p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
     <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  <title>WebAlbum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <% title = 'WebAlbum: ' +
         controller.controller_name.capitalize + ': ' +
         controller.action_name.capitalize %>
    <title><%= title %></title>
    <%= stylesheet_link_tag 'web_album' %>
</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>



         <% if user_signed_in? %> 
<a class="navbar-brand"  style="font-size:25px" <%= link_to 'WebAlbum', :action => 'index', :controller => 'albums' %>
   <% else %>
<a class="navbar-brand"  style="font-size:25px" <%= link_to 'WebAlbum' %>         
          <% end %>
          </a>
        </div>
        <div class="navbar-collapse collapse">
          
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>

            <li><a href="../navbar/"><%= current_user.email %></a></li>
            <li><%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %></li>
         
            <% else %>
           
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

<div class="container" style="margin-top:50px;">

<%= yield %>
</div>
<div class="container ">

<p class="notice" style="color:red;" ><%= notice %></p>
 <p class="alert" style="color:red;"><%= alert %></p>
</div>
 
</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>


  
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
  <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
 
  <%= f.hidden_field :album_id, :value => session[:albumID] %> <!-- accessing global parameter for the albumid -->
  </div>
  <div class="field">
    <%= f.label :content_type %><br>
    <%= f.text_field :content_type %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>


<h1 class="fancy">

  <% @@xx= params[:title] %></h1>

  <% if @@xx!= nil %>
  <% session[:albumID] = @@xx %>
  <% else %>
  <% end %>


 <div class="table-responsive">
            <table class="table table-striped">
              <thead>
    <tr>
      <th>Caption</th>
      <th>Description</th>

      <th>Content type</th>
      <th>Width</th>
      <th>Height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.caption %></td>
        <td><%= picture.description %></td>
        <td><%= picture.content_type %></td>
        <td><%= picture.width %></td>
        <td><%= picture.height %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p class="alert alert-info">Picture added</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/show/index.html.erb
<h1>Show#index</h1>
<% if user_signed_in? %>
  <p>Welcome <%= current_user.email %></p><p>Welcome <%= current_user.name %></p> 
  <%= link_to 'Logged In [click to logout]', destroy_user_session_path, :method => :delete %>
  
<% else %>
  <p>You are not signed in.</p>
  <%= link_to 'Login', new_user_session_path %>
<% end %>
<p>Find me in app/views/show/index.html.erb</p>